"""init mysql schema

Revision ID: 589a9279b3e0
Revises: 
Create Date: 2026-08-28 11:16:27.146442

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '589a9279b3e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('processed_pages', sa.Integer(), nullable=True),
    sa.Column('failed_pages', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_render_time', sa.Float(), nullable=True),
    sa.Column('total_ocr_time', sa.Float(), nullable=True),
    sa.Column('total_ai_time', sa.Float(), nullable=True),
    sa.Column('total_assembly_time', sa.Float(), nullable=True),
    sa.Column('output_zip_path', sa.String(length=1000), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index('idx_job_filename', 'jobs', ['filename'], unique=False)
    op.create_index('idx_job_status', 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('system_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stage1_queue_size', sa.Integer(), nullable=True),
    sa.Column('stage2_queue_size', sa.Integer(), nullable=True),
    sa.Column('stage3_queue_size', sa.Integer(), nullable=True),
    sa.Column('active_workers', sa.Integer(), nullable=True),
    sa.Column('active_ai_requests', sa.Integer(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('disk_usage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('pages_per_minute', sa.Float(), nullable=True),
    sa.Column('ai_requests_per_minute', sa.Float(), nullable=True),
    sa.Column('avg_render_latency', sa.Float(), nullable=True),
    sa.Column('avg_ocr_latency', sa.Float(), nullable=True),
    sa.Column('avg_ai_latency', sa.Float(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('total_errors', sa.Integer(), nullable=True),
    sa.Column('throughput_history', sa.Text(), nullable=True),
    sa.Column('eta_seconds', sa.Float(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_stats_job_id'), 'job_stats', ['job_id'], unique=True)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=1000), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('ocr_engine', sa.String(length=50), nullable=True),
    sa.Column('resolution_code', sa.String(length=200), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RENDERING', 'OCR_PROCESSING', 'AI_CLASSIFYING', 'COMPLETED', 'FAILED', name='pagestatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('render_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('render_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ocr_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ocr_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('render_duration', sa.Float(), nullable=True),
    sa.Column('ocr_duration', sa.Float(), nullable=True),
    sa.Column('ai_duration', sa.Float(), nullable=True),
    sa.Column('stage1_complete', sa.Boolean(), nullable=True),
    sa.Column('stage2_complete', sa.Boolean(), nullable=True),
    sa.Column('stage3_complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_page_job_id', 'pages', ['job_id'], unique=False)
    op.create_index('idx_page_page_number', 'pages', ['page_number'], unique=False)
    op.create_index('idx_page_resolution_code', 'pages', ['resolution_code'], unique=False)
    op.create_index('idx_page_stage1_complete', 'pages', ['stage1_complete'], unique=False)
    op.create_index('idx_page_stage2_complete', 'pages', ['stage2_complete'], unique=False)
    op.create_index('idx_page_status', 'pages', ['status'], unique=False)
    op.create_index(op.f('ix_pages_job_id'), 'pages', ['job_id'], unique=False)
    op.create_table('resolution_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('resolution_code', sa.String(length=200), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=False),
    sa.Column('end_page', sa.Integer(), nullable=False),
    sa.Column('output_pdf_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resolution_group_code', 'resolution_groups', ['resolution_code'], unique=False)
    op.create_index('idx_resolution_group_job_id', 'resolution_groups', ['job_id'], unique=False)
    op.create_index('idx_resolution_group_start_page', 'resolution_groups', ['start_page'], unique=False)
    op.create_index(op.f('ix_resolution_groups_job_id'), 'resolution_groups', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resolution_groups_job_id'), table_name='resolution_groups')
    op.drop_index('idx_resolution_group_start_page', table_name='resolution_groups')
    op.drop_index('idx_resolution_group_job_id', table_name='resolution_groups')
    op.drop_index('idx_resolution_group_code', table_name='resolution_groups')
    op.drop_table('resolution_groups')
    op.drop_index(op.f('ix_pages_job_id'), table_name='pages')
    op.drop_index('idx_page_status', table_name='pages')
    op.drop_index('idx_page_stage2_complete', table_name='pages')
    op.drop_index('idx_page_stage1_complete', table_name='pages')
    op.drop_index('idx_page_resolution_code', table_name='pages')
    op.drop_index('idx_page_page_number', table_name='pages')
    op.drop_index('idx_page_job_id', table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_job_stats_job_id'), table_name='job_stats')
    op.drop_table('job_stats')
    op.drop_table('system_stats')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index('idx_job_status', table_name='jobs')
    op.drop_index('idx_job_filename', table_name='jobs')
    op.drop_index('idx_job_created_at', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
